version: 1
update_configs:
  - package_manager: "go:dep"
    directory: "/"
    update_schedule: "weekly"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
